x-environment: &default-environment
  ENVIRONMENT_ACTIVE: local
  GTK_MODULES: canberra-gtk-module

services:
  ubuntu:
    image: ubuntu
    tty: true
    build:
      context: ..
      dockerfile: .devcontainer/containers/ubuntu/Dockerfile
    environment:
      <<: *default-environment
      DISPLAY: ${DISPLAY}
    volumes:
      - ..:/workspace
      - ~/.npmrc:/home/node/.npmrc:cached
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - $HOME/.aws:/home/ubuntu/.aws:rw
      - $HOME/.aws:/workspace/.aws:rw
      - $HOME/projetos:/workspace/projetos:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
    user: ubuntu
    privileged: true
    devices:
      - /dev/ppp
      - /dev/kvm
      - /dev/dri/card0
      - /dev/dri/renderD128
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    network_mode: "host"
